name: authentication_repository
description: Dart package which manages the authentication domain.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  cache:
    path: ../cache
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  supabase_flutter: ^1.2.2

  very_good_analysis: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.1
